# Site settings
title: Qsdfgh.com
email: pierre.lecocq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts, tech articles and snippets - By Pierre Lecocq.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://qsdfgh.com" # the base hostname & protocol for your site
safe: true

# Build settings
markdown: kramdown
